name: qgis-ext
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: geocompr/geocompr:qgis-ext
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Build book
          run: Rscript -e 'bookdown::render_book("index.Rmd")'
          
# 
# 
# jobs:
#   node-docker:
#     runs-on: ubuntu-latest
#     container:
#       image: geocompr/geocompr:qgis-ext
#     steps:
#          - name: Build book
#            run: Rscript -e 'bookdown::render_book("index.Rmd")'
    
        
